using System.Collections.ObjectModel;
using System.Diagnostics;
using Hexa.NET.ImGui;

namespace CentrED.UI;

/// <summary>
/// Maintains selection state for ImGui multi-select widgets and applies the selection
/// requests generated by ImGui back onto the caller's typed item collection.
/// </summary>
public class MultiSelectStorage<T>(HashSet<T> initialState)
{
    // Holds the current frame's input list so ImGui index-based selection requests can be
    // translated back into the caller's actual item instances.
    private List<T> _input = [];

    // The active set is initialized from the caller-provided state and then mutated in
    // place as ImGui emits selection operations.
    private HashSet<T> _selected = initialState;
    
    /// <summary>
    /// Begins an ImGui multi-select session for the current visible item list.
    /// Any queued selection requests from the start of the frame are applied immediately,
    /// and the clipper is told to keep the range anchor item alive for shift-selection.
    /// </summary>
    public void Begin(List<T> input, ImGuiListClipperPtr clipper, ImGuiMultiSelectFlags extraFlags = ImGuiMultiSelectFlags.None)
    {
        _input = input;

        // The editor manages explicit selection commands itself, so "select all" is always
        // disabled unless the calling code layers in additional ImGui flags.
        var flags = ImGuiMultiSelectFlags.NoSelectAll | extraFlags;
        var msIo = ImGui.BeginMultiSelect(flags, _selected.Count, input.Count);
        HandleRequests(msIo);

        // Range selection depends on the source item index remaining available even when a
        // clipper would otherwise skip it.
        if(msIo.RangeSrcItem != -1)
            clipper.IncludeItemByIndex((int)msIo.RangeSrcItem);
    }

    /// <summary>
    /// Ends the current ImGui multi-select session and applies any deferred selection
    /// requests that were produced while the list items were being drawn.
    /// </summary>
    public void End()
    {
        var msIo = ImGui.EndMultiSelect();
        HandleRequests(msIo);
    }
    
    /// <summary>
    /// Replays ImGui's selection requests against the current input list.
    /// ImGui reports changes in terms of item indices and bulk operations rather than by
    /// item identity, so this method is the bridge between the widget state and `_selected`.
    /// </summary>
    private void HandleRequests(ImGuiMultiSelectIOPtr msIo)
    {
        Debug.Assert(msIo.ItemsCount != -1, "Missing value for items_count in BeginMultiSelect() call!");
        Debug.Assert(msIo.ItemsCount == _input.Count, "Items count mismatched BeginMultiSelect() vs this.Begin()");
        for (var i = 0; i < msIo.Requests.Size; i++)
        {
            var req = msIo.Requests[i];
            if (req.Type == ImGuiSelectionRequestType.SetAll)
            {
                // "Set all" is modeled as replacing the entire selection rather than as a
                // sequence of individual adds/removes.
                _selected.Clear();
                if (req.Selected == 1)
                {
                    _selected = _input.ToHashSet();
                }
            }
            else if(req.Type == ImGuiSelectionRequestType.SetRange)
            {
                // Ranges are inclusive and expressed in the current input ordering.
                for (var j = req.RangeFirstItem; j <= req.RangeLastItem; j++)
                {
                    if (req.Selected == 1)
                    {
                        _selected.Add(_input[(int)j]);
                    }
                    else
                    {
                        _selected.Remove(_input[(int)j]);
                    }
                }
            }
        }
    }

    /// <summary>
    /// Replaces the current selection with a single item.
    /// </summary>
    public void SetSelection(T item)
    {
        _selected.Clear();
        _selected.Add(item);
    }

    /// <summary>
    /// Returns whether the given item is currently selected.
    /// </summary>
    public bool Contains(T n)
    {
        return _selected.Contains(n);
    }

    /// <summary>
    /// Exposes the current selection as a read-only set so callers can inspect it without
    /// mutating the storage directly.
    /// </summary>
    public ReadOnlySet<T> Items => _selected.AsReadOnly();
}